spring:
  datasource:
    url: jdbc:postgresql://first-ticket-postgres:5432/first_ticket
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: first-ticket-redis
      port: 6379
  kafka:
    bootstrap-servers: kafka:9092
