# queue-service에 환경 불문 항상 적용되는 설정
spring:
  application:
    name: queue-service

queue:
  token:
    waiting-ttl: PT30M           # ISO-8601 Duration: 30분
    admission-batch-size: 100    # 한 번에 100명 입장 승인
