# queue-service에 환경 불문 항상 적용되는 설정
spring:
  application:
    name: queue-service

queue:
  token:
    waiting-ttl: PT30M           # ISO-8601 Duration: 30분
    admission-batch-size: 100    # 한 번에 100명 입장 승인
  jwt:
    secret: '{cipher}0023905ba005ccc3bf20992038adb7eee7abe7d60f0db11c98ded4cc3b8cee3ea3e69a25696a1300a80cea532e9ec3864701668f67e8ac54034244d2b1afd89b'
    entry-token-ttl: PT3M        # 3 분
