server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/first_ticket
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual_immediate

common:
  messaging:
    scheduler:
      enabled: true

feature:
  internal-payments:
    enabled: true

toss:
  secret-key: '{cipher}e98def6b03fabc4c49aa9fe1852f90300a4f24de0359e52a9c3bfb26bc6c05b6a7cae83caac5020257351830da56ebaaab6b3cfebbb0b4ee2d8ec84da4a6a178%  '