server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/first_ticket
    username: postgres
    password:
  data:
    redis:
      host: localhost
      port: 6379
  flyway:
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

toss:
  secret-key: '{cipher}41da203e17de7526e41751252bffc8e117f8f89bfd1a9db0705025573704e11845c0c5a99ac0afcc58778d6bda3d6b69518835a1534e4772df489054287007d5'

common:
  messaging:
    scheduler:
      enabled: false

feature:
  internal-payments:
    enabled: true

payment:
  success-url: http://localhost:8084/api/v1/payments/confirm-redirect
  fail-url: http://localhost:8084/fail