spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_schema: payment_schema
        format_sql: true

  flyway:
    schemas: payment_schema
    default-schema: payment_schema
    create-schemas: true

kafka:
  topics:
    payment-completed: payment.completed
    payment-failed: payment.failed
    payment-refund-completed: payment.refund.completed
    booking-expired: booking.expired
    booking-cancel-requested: booking.cancel.requested
    booking-compensation: booking.payment.compensation