server:
  port: 8085

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

toss:
  secret-key: '{cipher}41da203e17de7526e41751252bffc8e117f8f89bfd1a9db0705025573704e11845c0c5a99ac0afcc58778d6bda3d6b69518835a1534e4772df489054287007d5'

common:
  messaging:
    scheduler:
      enabled: false

feature:
  internal-payments:
    enabled: true