server:
  port: 8085

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false

toss:
  secret-key: test_sk_6bJXmgo28e71a9Obm2JjVLAnGKWx