server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/payment
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

toss:
  secret-key: ${TOSS_SECRET_KEY}