# user-service 운영환경 설정
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:first-ticket-postgres}:5432/first_ticket
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 60
      minimum-idle: 10
      connection-timeout: 3000
      idle-timeout: 600000
      max-lifetime: 1800000

eureka:
  client:
    tls:
      enabled: false

keycloak:
  server-url: ${KEYCLOAK_SERVER_URL}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  admin-username: ${KEYCLOAK_ADMIN_USERNAME}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD}
  email-verified: true
