# user-service 기본 설정

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      # user-service 전용 스키마
      # public 스키마 대신 user_schema를 기본으로 사용 (서비스 간 테이블 격리)
      default_schema: user_schema
      dialect: org.hibernate.dialect.PostgresSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false #로컬에서만 true
    schemas: user_schema
    default-schema: user_schema
    create-schemas: true

  jackson:
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false

  datasource:
    # PostgreSQL JDBC 드라이버 명시
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    tls:
      enabled: false
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health, info

keycloak:
  realm: first-ticket
  client-id: user-client