# user-service 운영환경 설정
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:first-ticket-postgres}:5432/first_ticket
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

eureka:
  client:
    tls:
      enabled: true  # 운영 환경에서는  TLS 활성화

keycloak:
  server-url: ${KEYCLOAK_SERVER_URL}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  admin-username: ${KEYCLOAK_ADMIN_USERNAME}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD}
