spring:
  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: booking_schema
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    schemas: booking_schema
    default-schema: booking_schema
    create-schemas: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}