# ──────────────────────────────────────────
# venue-service.yaml (venue-service 공통 기본값)
# ──────────────────────────────────────────
spring:
  application:
    name: venue-service

  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_schema: venue_schema
        format_sql: true
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: venue_schema
    default-schema: venue_schema
    table: flyway_schema_history_venue
    create-schemas: true
