# ──────────────────────────────────────────
# program-service.yaml (공통 기본값)
# ──────────────────────────────────────────
spring:
  application:
    name: program-service

  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_schema: program_schema
        format_sql: true
    hibernate:
      ddl-auto: validate
      
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: program_schema
    default-schema: program_schema
    table: flyway_schema_history_program
